apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "parasol-insurance-tenant.prefix" . }}-pipeline-triggers
  annotations:
    argocd.argoproj.io/sync-wave: "0"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: openshift-pipelines-clusterinterceptors
subjects:
  - kind: ServiceAccount
    name: parasol-insurance-build
    namespace: {{ include "parasol-insurance-tenant.prefix" . }}-build
  - kind: ServiceAccount
    name: pipeline
    namespace: {{ include "parasol-insurance-tenant.prefix" . }}-build
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "parasol-insurance-tenant.prefix" . }}-webhook-setup
  annotations:
    argocd.argoproj.io/sync-wave: "0"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: {{ include "parasol-insurance-tenant.prefix" . }}
    namespace: {{ .Release.Namespace }}
