apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: {{ include "parasol-insurance-tenant.prefix" . }}-initial-build
  namespace: {{ include "parasol-insurance-tenant.prefix" . }}-build
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  pipelineRef:
    name: parasol-insurance-push
  params:
    - name: git-revision
      value: main
  workspaces:
    - name: source
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 2Gi
    - name: basic-auth
      secret:
        secretName: gitlab-basic-auth
    - name: dockerconfig
      secret:
        secretName: quay-push-secret
    - name: sonar-credentials
      secret:
        secretName: sonarqube-credentials
    - name: maven-cache
      persistentVolumeClaim:
        claimName: maven-cache
